# Change these first
owner: pearanalytics # Your GitHub username
repo: uptime # Your GitHub repository name
assignees: 
  - vidluther
# Add your sites here
sites:
  - name: Pear Dev Site 
    url: https://dev.pearanalytics.com
    headers: 
      - "Authorization: Basic $AUTH_PEARDEVSITE"
  - name: pearanalytics
    url: https://pearanalytics.com
  - name: fladvisors
    url: https://fladvisors.com
  - name: copc
    url: https://copc.com
  - name: universalbb
    url: https://universalbookbindery.com
  - name: concussionguy
    url: https://concussionguy.com
  - name: copccopy
    url: https://copccopy.wpengine.com
  - name: alamonote
    url: https://alamonote.wpengine.com
  - name: shirane
    url: https://shiranefoundation.org
  - name: intranetpear
    url: https://intranetpear.wpengine.com
    headers: 
      - "Authorization: Basic $AUTH_PEARINTRANET"
  - name: aceschoolorg
    url: http://aceschoolorg.wpengine.com
  - name: eharris
    url: https://eharris.wpengine.com
  - name: bhrnew
    url: https://berkshirehairremoval.com
  - name: findingstax
    url: https://findingstax.wpengine.com
  - name: acadian
    url: https://acadianlogistics.com
  - name: beaconunited2
    url: http://beacon-united.com
  - name: strauch
    url: https://www.strauchlaw.com
  - name: copcnew
    url: https://www.copc.com
  - name: amazingair
    url: https://amazingairsolutions.co
  - name: firsttexan
    url: https://firsttexanrealty.com
  - name: najim
    url: https://najimfoundation.org
  - name: contegoim
    url: https://contegoim.com
  - name: alamomineral
    url: https://alamomineralbuyers.com
  - name: alamohomebuyer
    url: https://alamohomebuyers.com
  - name: sanotebuyer
    url: https://sanotebuyer.wpengine.com
  - name: sahomebuyer
    url: https://sahomebuyer.wpengine.com
  - name: fascinationsp
    url: https://fascinationstreetpod.com
  - name: alamobuyers
    url: https://alamobuyers.com
  - name: tluadm
    url: https://tluadm.wpengine.com
  - name: saparksfound
    url: https://saparksfoundation.org
  - name: sabuyers
    url: https://sabuyers.wpengine.com
  - name: sabuyer
    url: https://sabuyer.wpengine.com
  - name: sellmyplace
    url: https://sellmyplace.wpengine.com
  - name: sellmynote
    url: https://sellmynote.com
  - name: sandlersa
    url: https://sandlersa.wpengine.com
  - name: yokelfinancial
    url: https://yokelfinancial.wpengine.com
  - name: copcprocure
    url: https://copcprocure.wpengine.com
  - name: jsbhs
    url: https://jsbhs.wpengine.com
  - name: ehrenberg
    url: https://ehrenberg.wpengine.com
  - name: eharrisv2
    url: https://www.eharrismd.com
  - name: riachueloranch
    url: https://riachueloranch.com
  - name: ignitecc
    url: https://ignitecommunity.church
  - name: idpsalientup
    url: https://indirectpro.com
  # - name: copcsalientup
  #   url: https://copcsalientup.wpengine.com
  - name: hartmanfound
    url: https://gordonhartman.com
  - name: hotshotfinal
    url: https://hotshotfinalmile.com
  - name: workatmercho
    url: https://workatmerchco.com
  - name: merchcomain
    url: https://merchcoservices.com
  # - name: ibuysa
  #   url: https://ibuysa.wpengine.com
  - name: hdnew
    url: https://www.thetriallawyers.com
  - name: tuyatech
    url: https://tuyatech.com
  - name: alamofireworks
    url: https://www.alamofireworks.com
  # - name: beeclean
  #   url: https://beeclean.wpengine.com
  # - name: siteowl
  #   url: https://siteowl.wpengine.com
  # - name: emmajanev1
  #   url: https://emmajanev1.wpengine.com
  - name: robinsonvm
    url: https://www.robinsonvalue.com
  - name: edgecombe
    url: https://edgecombe.com
  - name: lesauce
    url: https://lesauce.wpengine.com
  # - name: beecleanold
  #   url: https://beecleanold.wpengine.com
  - name: sacounselors
    url: https://sacounselors.wpengine.com
  # - name: riptidewash
  #   url: https://riptideautowashes.com
  - name: officefurnliq
    url: https://www.officefurnituresa.com
  - name: espronceda
    url: https://alamodivorcelawyer.com
  # - name: unrealdigital
  #   url: https://www.unrealdigitalgroup.com
  # - name: npinaction
  #   url: https://nonprofitsinaction.org
  # - name: riptideuvalde
  #   url: https://uvaldecarwash.com
  # - name: logopop
  #   url: https://thelogopop.com
  - name: xenexlive
    url: https://xenex.com
  - name: allenlive
    url: https://lumberhardware.com
  # - name: nomaskspatriot
  #   url: https://nomaskspatriot.wpengine.com
status-page:
  robotsText: "User-agent: * \n Disallow: /"
  
status-website:
  publish: true
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.pearanalytics.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /uptime
  name: Uptime Monitor
  metaTags:
    - name: "robots"
      content: "noindex"
  logoUrl: https://pearanalytics.com/wp-content/uploads/2019/04/logo.png
  introTitle: "Client Uptime Monitor"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: PearAnalytics
      href: https://pearanalytics.com/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
