# Change these first
owner: pearanalytics # Your GitHub username
repo: uptime # Your GitHub repository name
assignees: 
  - vidluther
# Add your sites here
sites:
  - name: PearAnalytics 
    url: https://pearanalytics.com
    maxResponseTime: 2000
  - name: EdgeCombe
    url: https://edgecombe.com
  - name: SA Parks Foundation
    url: https://saparksfoundation.org
  - name: Site Owl
    url: https://getsiteowl.com
  - name: Harrison Davis (The Trial Lawyers)
    url: https://www.thetriallawyers.com
  - name: Le Sauce Company
    url: https://lesaucecompany.com
  - name: Elizabeth Harris
    url: https://eharrismd.com
    maxResponseTime: 2000
  - name: MerchCo
    url: https://merchcoservices.com
  - name: Robinson Value Management
    url: https://robinsonvalue.com
  - name: VP Racing Fuels
    url: https://vpracingfuels.com
    maxResponseTime: 2000
  - name: COPC
    url: https://copc.com
    maxResponseTime: 2000
  - name: South Texas Guns
    url: https://southtexasguns.com
    maxResponseTime: 2000
  - name: Office Furniture SA
    url: https://www.officefurnituresa.com
    maxResponseTime: 2000
  - name: Hartman Foundation
    url: https://gordonhartman.com/
    maxResponseTime: 6000
  - name: Xenex
    url: https://xenex.com/
    maxResponseTime: 2000
  - name: Pencil for Schools
    url: https://pencilforschools.org/
    maxResponseTime: 2000
  - name: Google
    url: https://www.google.com
  - name: Example Broken Site
    url: https://thissitedoesnotexist.com
  - name: Luther.io
    url: http://luther.io
  - name: Gate Test Environment
    url: https://pearanalytics.wp.gate.com/
  - name: Hot Shot Final Mile
    url: https://hotshotfinalmile.com/
  - name: Tuya Tech
    url: https://tuyatech.com/
  - name: American Fence and Deck
    url: https://americanfencedeck.com

status-page:
  robotsText: "User-agent: * \n Disallow: /"
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.pearanalytics.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /uptime
  name: Uptime Monitor
  metaTags:
    - name: "robots"
      content: "noindex"
  logoUrl: https://pearanalytics.com/wp-content/uploads/2019/04/logo.png
  introTitle: "Client Uptime Monitor"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: PearAnalytics
      href: https://pearanalytics.com/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
