# Change these first
owner: pearanalytics # Your GitHub username
repo: uptime # Your GitHub repository name
assignees: 
  - vidluther
# Add your sites here
sites:
  - name: PearAnalytics
    url: https://pearanalytics.com
  - name: hotshotfinal
    primary_domain: hotshotfinalmile.com
  - name: workatmercho
    primary_domain: workatmerchco.com
  - name: merchcomain
    primary_domain: merchcoservices.com
  - name: ibuysa
    primary_domain: ibuysa.wpengine.com
  - name: hdnew
    primary_domain: www.thetriallawyers.com
  - name: tuyatech
    primary_domain: tuyatech.com
  - name: alamofireworks
    primary_domain: www.alamofireworks.com
  - name: beeclean
    primary_domain: beecleanwash.com
  - name: siteowl
    primary_domain: siteowl.wpengine.com
  - name: emmajanev1
    primary_domain: emmajanev1.wpengine.com
  - name: robinsonvm
    primary_domain: www.robinsonvalue.com
  - name: edgecombe
    primary_domain: edgecombe.com
  - name: lesauce
    primary_domain: lesauce.wpengine.com
  - name: beecleanold
    primary_domain: beecleanold.wpengine.com
  - name: mdunnebrands
    primary_domain: dunnebrands.com
  - name: sacounselors
    primary_domain: sacounselors.wpengine.com
  - name: riptidewash
    primary_domain: riptideautowashes.com
  - name: officefurnliq
    primary_domain: www.officefurnituresa.com
  - name: espronceda
    primary_domain: alamodivorcelawyer.com
  - name: unrealdigital
    primary_domain: www.unrealdigitalgroup.com
  - name: npinaction
    primary_domain: nonprofitsinaction.org
  - name: riptideuvalde
    primary_domain: uvaldecarwash.com
  - name: logopop
    primary_domain: thelogopop.com
  - name: xenexlive
    primary_domain: xenex.com
  - name: allenlive
    primary_domain: lumberhardware.com
  - name: strikeforceuv
    primary_domain: strikeforceuv.com
  - name: nomaskspatriot
    primary_domain: nomaskspatriot.wpengine.com
status-page:
  robotsText: "User-agent: * \n Disallow: /"
  
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: uptime.pearanalytics.com
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /uptime
  name: Uptime Monitor
  metaTags:
    - name: "robots"
      content: "noindex"
  logoUrl: https://pearanalytics.com/wp-content/uploads/2019/04/logo.png
  introTitle: "Client Uptime Monitor"
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: PearAnalytics
      href: https://pearanalytics.com/
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
